export const RECEIVE_ADDRESS = 'receive_address' // 根据经纬度获取位置详情
export const RECEIVE_FOODSTYPE = 'receive_foodstype' // 获取食品分类列表
export const RECEIVE_SHOPLIST = 'receive_shoplist' // 根据经纬度获取商铺列表
export const RECEIVE_USERINFO = 'receive_userinfo' // 同步获取用户登陆信息
export const RECEIVE_GETOUT = 'receive_getout' // 用户登出
export const RECEIVE_GETSHOPGOODS = 'receive_getshopgoods' // 获取商店商品
export const RECEIVE_GETSHOPINFO = 'receive_getshopinfo' // 获取商店商品
export const RECEIVE_GETSHOPRATING = 'receive_getshoprating' // 获取商店商品
export const INCRESE_COUNT = 'increse_count'// 增加购物车商品
export const DECRESE_COUNT = 'decrese_count'// 减少购物车商品
export const CLEANCART = 'cleancart'// 清空购物车商品
export const RECEIVE_SEARCHLIST = 'receive_searchlist' // 根据经纬度和关键字搜索商铺列表
